var x = 6;
var y = 10;
console.log(x++);
console.log(4 == 4);
console.log(2 > 1);
console.log(89 >= 29);
console.log(13 < 12);
console.log(x < y);
console.log('hello' != 'Hello');
console.log(2 === 2);
console.log(2 === '2');
console.log(true && true);
console.log(true && false);
console.log(true || false);
console.log(!true);
console.log('hello ' + 'world');
let text1 = "What a very ";
text1 += "nice day";
console.log(text1);
console.log("5" + 5);
console.log("Hello" + 5);